# Generated by Django 3.1.2 on 2020-10-19 12:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('desc', models.TextField(blank=True, null=True)),
                ('task_status', models.CharField(choices=[('planning', 'planning'), ('active', 'active'), ('inactive', 'inactive'), ('testing', 'testing'), ('completed', 'completed'), ('failed', 'failed')], max_length=64)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('planned_end', models.DateTimeField(blank=True, null=True)),
                ('observers_id', models.ManyToManyField(related_name='task_id', to=settings.AUTH_USER_MODEL)),
                ('operator_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TaskStatusUpdate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prev_status', models.CharField(choices=[('planning', 'planning'), ('active', 'active'), ('inactive', 'inactive'), ('testing', 'testing'), ('completed', 'completed'), ('failed', 'failed')], max_length=64)),
                ('next_status', models.CharField(choices=[('planning', 'planning'), ('active', 'active'), ('inactive', 'inactive'), ('testing', 'testing'), ('completed', 'completed'), ('failed', 'failed')], max_length=64)),
                ('update_time', models.DateTimeField(blank=True, null=True)),
                ('editor_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('task_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.task')),
            ],
        ),
    ]
