# Generated by Django 3.1.2 on 2020-11-04 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20201030_1427'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskreminder',
            name='is_failed',
        ),
        migrations.AddField(
            model_name='taskreminder',
            name='reason',
            field=models.CharField(blank=True, choices=[('planning', 'planning'), ('active', 'active'), ('inactive', 'inactive'), ('testing', 'testing'), ('completed', 'completed'), ('failed', 'failed')], max_length=32, null=True),
        ),
    ]
