# Generated by Django 3.1.2 on 2020-11-05 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20201104_0456'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='last_update',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='taskreminder',
            name='sent_properly',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
